name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
       host port: 3800
       container port: 3307
       character set server: 'utf8'
       collation server: 'utf8_general_ci'
       mysql database: 'listes' # Optional, default value is "test". The specified database which will be create
       mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
       mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
       mysql password: 'root'
     
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run:  composer install --ignore-platform-reqs
    - name: create dataBase
      run: php bin/console d:d:c
    - name: teste intaire
      run: php bin/phpunit
